# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  #  push:
  #    branches: [ master ]
  #  pull_request:
  #    branches: [ master ]
  repository_dispatch:
  watch:
    types: [ started ] # 有人点星星就执行
  schedule: # 注意这是UTC时间，有时差，16点对应的是北京时间0点
    - cron: '0 19 * * *' # 早上7点执行一次

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: 安装
        run: yarn install

      - name: 运行
        run: npm run start
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
          AZURE_EMAIL: ${{ secrets.AZURE_EMAIL }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          ACFUN_UID: ${{ secrets.ACFUN_UID }}
          ACFUN_TOKEN: ${{ secrets.ACFUN_TOKEN }}
